const LOAD_COMMENTS_DATA_SUCCESS = 'App/LOAD_COMMENTS_DATA_SUCCESS';
const LOAD_COMMENTS_DATA_FAILURE = 'App/LOAD_COMMENTS_DATA_FAILURE';
const LOAD_COMMENTS_DATA_STARTED = 'App/LOAD_COMMENTS_DATA_STARTED';

export {
	LOAD_COMMENTS_DATA_SUCCESS,
	LOAD_COMMENTS_DATA_FAILURE,
	LOAD_COMMENTS_DATA_STARTED,
};
