const LOAD_DATA_SUCCESS = 'App/LOAD_DATA_SUCCESS';
const LOAD_DATA_FAILURE = 'App/LOAD_DATA_FAILURE';
const LOAD_DATA_STARTED = 'App/LOAD_DATA_STARTED';

export { LOAD_DATA_SUCCESS, LOAD_DATA_FAILURE, LOAD_DATA_STARTED };
